/**
 * Common constants used across API services
 */

/**
 * Common fields that typically contain the title/name of an item
 * Used for consistent title extraction across the codebase
 */
export const TITLE_FIELDS = ['title', 'name', 'headline', 'label', 'heading'] as const;

/**
 * System metadata fields that should be excluded when copying items
 * These fields are auto-generated by Directus
 */
export const METADATA_FIELDS = ['id', 'user_created', 'user_updated', 'date_created', 'date_updated'] as const;

/**
 * Parse allowed collections from various formats
 * @param allowedCollections The allowed collections in various formats
 * @returns Array of collection names
 */
export function parseAllowedCollections(
  allowedCollections: string[] | string | undefined
): string[] {
  if (!allowedCollections) {
    return [];
  }
  
  if (Array.isArray(allowedCollections)) {
    return allowedCollections;
  }
  
  // Handle comma-separated string format
  if (typeof allowedCollections === 'string') {
    return allowedCollections
      .split(',')
      .map(c => c.trim())
      .filter(c => c.length > 0);
  }
  
  return [];
}