/**
 * Helper functions for expandable-blocks extension
 */

import type { JunctionRecord, ItemRecord, CollectionInfo } from '../types';
import { deepEqual, deepClone } from './state-helpers';
import { isTemporaryId } from './validation';

/**
 * Common fields that typically contain the title/name of an item
 * Used for consistent title extraction across the codebase
 */
export const TITLE_FIELDS = ['title', 'name', 'headline', 'label', 'heading'] as const;

/**
 * System metadata fields that should be excluded when copying items
 * These fields are auto-generated by Directus
 */
export const METADATA_FIELDS = ['id', 'user_created', 'user_updated', 'date_created', 'date_updated'] as const;

/**
 * Build fields string for M2A queries
 */
export function buildM2AFieldsString(allowedCollections: CollectionInfo[]): string {
  if (allowedCollections.length === 0) {
    return '*,item.*';
  }
  
  const itemFields = allowedCollections
    .map(col => `item:${col.collection}.*`)
    .join(',');
  
  return `*,${itemFields}`;
}

/**
 * Extract title from item data
 */
export function extractItemTitle(item: ItemRecord | JunctionRecord): string {
  // First check if item is an object before using 'in' operator
  if (!item || typeof item !== 'object') {
    return 'Untitled Block';
  }
  
  const itemData = 'item' in item && typeof item.item === 'object' 
    ? item.item 
    : item;
  
  if (!itemData || typeof itemData !== 'object') {
    return 'Untitled Block';
  }
  
  // Check each title field in order of preference
  for (const field of TITLE_FIELDS) {
    const value = (itemData as any)[field];
    if (value && typeof value === 'string') {
      return value;
    }
  }
  
  return 'Untitled Block';
}

/**
 * Get actual item ID from junction record
 */
export function getActualItemId(item: JunctionRecord): string | number {
  if (item.item && typeof item.item === 'object') {
    return item.item.id;
  }
  return item.id;
}

/**
 * Check if item is new (not saved to database)
 */
export function isNewItem(item: JunctionRecord): boolean {
  return isTemporaryId(item.id);
}

/**
 * Parse allowed collections from various formats
 */
export function parseAllowedCollections(
  allowedCollections: string[] | string | undefined
): string[] {
  if (!allowedCollections) return [];
  
  if (Array.isArray(allowedCollections)) {
    return allowedCollections;
  }
  
  if (typeof allowedCollections === 'string') {
    return allowedCollections
      .split(',')
      .map(c => c.trim())
      .filter(c => c.length > 0);
  }
  
  return [];
}

/**
 * Get the actual item from a junction record
 * Junction records can have nested items, this extracts the actual item data
 * @param item - The junction record or item
 * @returns The actual item data
 */
export function getActualItem(item: JunctionRecord | ItemRecord): ItemRecord {
  return (item as JunctionRecord).item || item;
}

/**
 * Extract collection name from an item
 * Tries multiple strategies to find the collection name
 * @param item - The junction record or item
 * @returns The collection name or undefined
 */
export function getItemCollection(item: JunctionRecord | ItemRecord): string | undefined {
  const actualItem = getActualItem(item);
  
  // First try the junction record's collection
  if ('collection' in item && item.collection) {
    return item.collection;
  }
  
  // Then try the actual item's collection
  if (actualItem && typeof actualItem === 'object' && 'collection' in actualItem) {
    return actualItem.collection;
  }
  
  return undefined;
}

/**
 * Add junction metadata (foreign key and sort field) to an item
 * @param item - The junction record to add metadata to
 * @param foreignKeyField - The foreign key field name
 * @param foreignKeyValue - The foreign key value to set
 * @param sortField - The sort field name (optional)
 * @param sortValue - The sort value to set (optional)
 */
export function addJunctionMetadata(
  item: JunctionRecord,
  foreignKeyField?: string,
  foreignKeyValue?: string | number,
  sortField?: string,
  sortValue?: number
): void {
  // Add foreign key if provided
  if (foreignKeyField && foreignKeyValue !== undefined) {
    (item as any)[foreignKeyField] = foreignKeyValue;
  }
  
  // Add sort value if provided
  if (sortField && sortValue !== undefined) {
    (item as any)[sortField] = sortValue;
  }
}

// Re-export deepEqual and deepClone for backward compatibility
export { deepEqual, deepClone };